services:
  - type: web
    name: recipe-django-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn Recipe_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.4

databases:
  - name: recipe-db
    plan: free
