services:
  - type: web
    name: recipe-django-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: Recipe_project.settings
      - key: PYTHON_VERSION
        value: 3.13.0

databases:
  - name: recipe-db
    plan: free
